### ISSUE TITLE
[Suggestion] Allow text box growth direction and width customization

### ISSUE THREAD

**Issue by justinrusso** [Darkhax-Minecraft/Tips#2]
In the default offset, some tips I am using are being cut off as it the text area for the tips expand below the max height of the window.

I noticed that the text box area also feels less wide and when full screened may take up only half of my 1080p monitor. If possible, could the width scale with window size?

**Comment by darkhax** [comment]
The wrap length for the tooltip is set to half the size of the current window. This was the easiest way to allow scaling for different window sizes. I don't really know of an elegant way to make that configurable in a meaningful way. 

There was also a bug with the X coordinate not being scaled to the monitor resolution. This is fixed in the next version.
