### ISSUE TITLE
[suggestion] tips alignment and positioning 

### ISSUE THREAD

**Issue by V4NK0V** [Darkhax-Minecraft/Tips#54]
It'd be nice if in tips config file you could move (or stretch) tip line all across the screen, so tips with big amount of characters will not just stays in left bottom corner.

**Comment by Drigonis** [comment]
i second this.
alternatively, i think it would be good if you could make the tips appear on the right side

**Comment by Darkhax** [comment]
Thanks for the suggestion, unfortunately I don't have any plans to add this. This was a feature in the past however rendering is not very intuitive and most of the issue reports I received were from people with bad config changes. Making this non-configurable also helps make the mod more maintainable as I can use dynamic values rather than static values from the config, and adjust the rendering code based on the screen size of the user.
