### ISSUE TITLE
[suggestion] incomplete German translation

### ISSUE THREAD

**Issue by DancerVlt69** [Darkhax-Minecraft/Tips#66]
I've saw the German translation is incomplete. At https://github.com/DancerVlt69/Tips/blob/1.18.2/Common/src/main/resources/assets/tipsmod/lang/de_de.json  you can find the rest with one extra Tip. The json file: https://github.com/DancerVlt69/Tips/blob/1.18.2/Common/src/main/resources/assets/tipsmod/tips/cave_spider.json

**Comment by Darkhax** [comment]
Thanks for updating the localization. I've added it for 1.18.2 and will bring it to 1.19+ soon. I did not include the cave spider tip because I don't think it's widely applicable enough. I may try to add an inspired tip that reminds players about small hostile mobs like cave spiders and baby zombies that can get through 1 block holes.

**Comment by DancerVlt69** [comment]
- cave spider: One-Block-Mod-Tip, that's sounds better!

By the way: 
- the 1.19.1 version of the mod works also fine in 1.19.2 ;)
- do you plan an update for MC 1.16.5?
