### ISSUE TITLE
[Suggestion] "Tip book" item

### ISSUE THREAD

**Issue by ProspectPyxis** [Darkhax-Minecraft/Tips#7]
There should be some sort of item that allows you to view every registered tip, in case you miss anything that might be useful. Optionally tied to a config option as well so you could disable the item if you want.

**Comment by darkhax** [comment]
Thanks for the suggestion, this is a good idea. I want to avoid adding new items because that changes how the mod interacts with servers. Currently if this mod is installed on a server, the players can remove or disable the mod if they don't want to use it. Support for this behavior is very important for client QOL mods like Tips. I think a decent solution to this would be to use the vanilla book item and fill that with the tips instead. The item could then be given by a command or potentially be a loot item.

**Comment by Darkhax** [comment]
In the 1.16.3 update all tip data has been moved to the client so it is no longer possible to implement this. Modpacks still have the tools to make their own books though, especially now that patchouli exists.
